### ISSUE TITLE
Blood drop emoji doesn't work

### ISSUE THREAD

**Issue by mohitaksh** [kabirsingh2004/A-Advance-Discord-Music-Bot-Like-Hydra-#12]
/root/bot/bot/node_modules/discord.js/src/rest/RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Cannot send messages to this user
    at RequestHandler.execute (/root/bot/bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/root/bot/bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/931817708390072360/messages',
  code: 50007,
  httpStatus: 403
}

**Comment by kabirsingh2004** [comment]
dm is disabled of user
